<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '90fc2392e28f871c2137f9345df774d3',
  'DATABASE_URL' => 'mysql://fipo6332_pommine:P2Or4yAdj0ji12op@pommine-/fipo6332_realnews?serverVersion=mariadb-10.3.32',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
